build:
    version: "3.0"

accounts:
    message: "Welcome to Eazybanks accounts microservice for dev environment"
    contactDetails:
        name: "John Doe - Developer"
        email: "doe@eazybanks.com"
    onCallSupport:
        - (555) 555-5553
        - (555) 555-5554